-- MySQL Script generated by MySQL Workbench
-- Thu May  5 19:47:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`workers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `shifts` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shifts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `turn` VARCHAR(45) NOT NULL,
  `hours` INT NOT NULL,
  `workersId` INT NOT NULL,
  PRIMARY KEY (`id`, `workersId`),
  INDEX `fk_shifts_workers1_idx` (`workersId` ASC) VISIBLE,
  CONSTRAINT `fk_shifts_workers1`
    FOREIGN KEY (`workersId`)
    REFERENCES `mydb`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `items` INT NOT NULL,
  `weight` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`books` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `cargoesId` INT NOT NULL,
  PRIMARY KEY (`id`, `cargoesId`),
  INDEX `fk_books_cargoes1_idx` (`cargoesId` ASC) VISIBLE,
  CONSTRAINT `fk_books_cargoes1`
    FOREIGN KEY (`cargoesId`)
    REFERENCES `mydb`.`cargoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'The book types can be: hardcover, paperback or digital';


-- -----------------------------------------------------
-- Table `mydb`.`booksForLend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booksForLend` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `editorial` VARCHAR(45) NOT NULL,
  `ESN` INT NOT NULL,
  `booksId` INT UNSIGNED NOT NULL,
  `booksCargoesId` INT NOT NULL,
  PRIMARY KEY (`id`, `books_id`, `books_cargoes_id`),
  UNIQUE INDEX `ESN_UNIQUE` (`ESN` ASC) VISIBLE,
  INDEX `fk_booksForLend_books1_idx` (`books_id` ASC, `books_cargoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_booksForLend_books1`
    FOREIGN KEY (`books_id` , `books_cargoes_id`)
    REFERENCES `mydb`.`books` (`id` , `cargoesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`booksForSale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booksForSale` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `editorial` VARCHAR(45) NOT NULL,
  `type` INT NOT NULL,
  `booksId` INT UNSIGNED NOT NULL,
  `booksCargoesId` INT NOT NULL,
  PRIMARY KEY (`id`, `booksId`, `booksCargoesId`),
  INDEX `fk_booksForSell_books1_idx` (`booksId` ASC, `booksCargoesId` ASC) VISIBLE,
  CONSTRAINT `fk_booksForSell_books1`
    FOREIGN KEY (`booksId` , `booksCargoesId`)
    REFERENCES `mydb`.`books` (`id` , `cargoesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customersId` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `customersId`),
  INDEX `fk_orders_customers1_idx` (`customersId` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customersId`)
    REFERENCES `mydb`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shippingType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shippingType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'shipping types: 2 day shipment, 1 week shipment or next day';


-- -----------------------------------------------------
-- Table `mydb`.`payMethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payMethod` (
  `id`  NOT NULL,
  `method` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordersDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordersDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ordersId` INT NOT NULL,
  `booksForSaleId` INT NOT NULL,
  `workersId` INT NOT NULL,
  `shippingTypeId` INT NOT NULL,
  `payMethodId` INT NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `totalOrder` INT NOT NULL,
  PRIMARY KEY (`id`, `ordersId`, `booksForSaleId`, `workersId`, `shippingTypeId`, `payMethodId`),
  INDEX `fk_orders_has_forSell_forSell1_idx` (`booksForSaleId` ASC) VISIBLE,
  INDEX `fk_orders_has_forSell_orders1_idx` (`ordersId` ASC) VISIBLE,
  INDEX `fk_ordersDetails_workers1_idx` (`workersId` ASC) VISIBLE,
  INDEX `fk_ordersDetails_Shipping1_idx` (`shippingTypeId` ASC) VISIBLE,
  INDEX `fk_ordersDetails_payMethod1_idx` (`payMethodId` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_forSell_orders1`
    FOREIGN KEY (`ordersId`)
    REFERENCES `mydb`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_forSell_forSell1`
    FOREIGN KEY (`booksForSaleId`)
    REFERENCES `mydb`.`booksForSale` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordersDetails_workers1`
    FOREIGN KEY (`workersId`)
    REFERENCES `mydb`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordersDetails_Shipping1`
    FOREIGN KEY (`shippingTypeId`)
    REFERENCES `mydb`.`shippingType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordersDetails_payMethod1`
    FOREIGN KEY (`payMethodId`)
    REFERENCES `mydb`.`payMethod` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usersId` INT NOT NULL,
  PRIMARY KEY (`id`, `users_idusers`),
  INDEX `fk_lends_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_lends_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lendsDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lendsDetail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lendsId` INT NOT NULL,
  `workersId` INT NOT NULL,
  PRIMARY KEY (`id`, `workersId`, `lendsId`),
  INDEX `fk_forLend_has_lends_lends1_idx` (`lendsId` ASC) VISIBLE,
  INDEX `fk_forLend_has_lends_forLend1_idx` (`id` ASC) VISIBLE,
  INDEX `fk_forLend_has_lends_workers1_idx` (`workersId` ASC) VISIBLE,
  CONSTRAINT `fk_forLend_has_lends_forLend1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`booksForLend` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forLend_has_lends_lends1`
    FOREIGN KEY (`lendsId`)
    REFERENCES `mydb`.`lends` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forLend_has_lends_workers1`
    FOREIGN KEY (`workersId`)
    REFERENCES `mydb`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cargoDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cargoDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cargoesId` INT NOT NULL,
  `workersId` INT NOT NULL,
  PRIMARY KEY (`id`, `cargoesId`, `workersId`),
  INDEX `fk_cargoes_has_workers_workers2_idx` (`workersId` ASC) VISIBLE,
  INDEX `fk_cargoes_has_workers_cargoes2_idx` (`cargoesId` ASC) VISIBLE,
  CONSTRAINT `fk_cargoes_has_workers_cargoes2`
    FOREIGN KEY (`cargoesId`)
    REFERENCES `mydb`.`cargoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cargoes_has_workers_workers2`
    FOREIGN KEY (`workersId`)
    REFERENCES `mydb`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
